[2023-09-23T12:54:13.000+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: create_tables.create_users_table manual__2023-09-23T12:54:12.321135+00:00 [queued]>
[2023-09-23T12:54:13.015+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: create_tables.create_users_table manual__2023-09-23T12:54:12.321135+00:00 [queued]>
[2023-09-23T12:54:13.016+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-09-23T12:54:13.017+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-09-23T12:54:13.018+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-09-23T12:54:13.033+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_users_table> on 2023-09-23 12:54:12.321135+00:00
[2023-09-23T12:54:13.040+0000] {standard_task_runner.py:55} INFO - Started process 6973 to run task
[2023-09-23T12:54:13.043+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_tables', 'create_users_table', 'manual__2023-09-23T12:54:12.321135+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/process_data.py', '--cfg-path', '/tmp/tmpyeqeohd9']
[2023-09-23T12:54:13.044+0000] {standard_task_runner.py:83} INFO - Job 86: Subtask create_users_table
[2023-09-23T12:54:13.114+0000] {task_command.py:376} INFO - Running <TaskInstance: create_tables.create_users_table manual__2023-09-23T12:54:12.321135+00:00 [running]> on host 20e0c20d2e1d
[2023-09-23T12:54:13.181+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_tables
AIRFLOW_CTX_TASK_ID=create_users_table
AIRFLOW_CTX_EXECUTION_DATE=2023-09-23T12:54:12.321135+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-23T12:54:12.321135+00:00
[2023-09-23T12:54:13.191+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-09-23T12:54:13.195+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users(
                first_name TEXT NULL,
                last_name TEXT NULL,
                email TEXT NULL,
                street_number SMALLINT NULL,
                street_name TEXT NULL,
                surburb TEXT NULL,
                post_code INTEGER NULL,
                state TEXT NULL,
                country TEXT NULL
            );
        , parameters: None
[2023-09-23T12:54:13.196+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2023-09-23T12:54:13.208+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=create_tables, task_id=create_users_table, execution_date=20230923T125412, start_date=20230923T125413, end_date=20230923T125413
[2023-09-23T12:54:13.257+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-09-23T12:54:13.290+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
