[2023-09-20T11:14:15.723+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: copy_data_between_databases.extract_data_task scheduled__2023-09-19T00:00:00+00:00 [queued]>
[2023-09-20T11:14:15.736+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: copy_data_between_databases.extract_data_task scheduled__2023-09-19T00:00:00+00:00 [queued]>
[2023-09-20T11:14:15.737+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-09-20T11:14:15.738+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-09-20T11:14:15.738+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-09-20T11:14:15.753+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): extract_data_task> on 2023-09-19 00:00:00+00:00
[2023-09-20T11:14:15.760+0000] {standard_task_runner.py:55} INFO - Started process 11736 to run task
[2023-09-20T11:14:15.771+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'copy_data_between_databases', 'extract_data_task', 'scheduled__2023-09-19T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/extract_data.py', '--cfg-path', '/tmp/tmpv13ttht1']
[2023-09-20T11:14:15.772+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask extract_data_task
[2023-09-20T11:14:15.875+0000] {task_command.py:376} INFO - Running <TaskInstance: copy_data_between_databases.extract_data_task scheduled__2023-09-19T00:00:00+00:00 [running]> on host 411713a30e55
[2023-09-20T11:14:15.964+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=copy_data_between_databases
AIRFLOW_CTX_TASK_ID=extract_data_task
AIRFLOW_CTX_EXECUTION_DATE=2023-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-19T00:00:00+00:00
[2023-09-20T11:14:15.982+0000] {logging_mixin.py:120} INFO - Error: unsupported format character 'i' (0x69) at index 56
[2023-09-20T11:14:15.983+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-09-20T11:14:15.996+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=copy_data_between_databases, task_id=extract_data_task, execution_date=20230919T000000, start_date=20230920T111415, end_date=20230920T111415
[2023-09-20T11:14:16.022+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-09-20T11:14:16.041+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
