[2023-09-28T22:24:00.847+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: create_tables.create_MLcustomer_table scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-09-28T22:24:00.862+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: create_tables.create_MLcustomer_table scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-09-28T22:24:00.863+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-09-28T22:24:00.864+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-09-28T22:24:00.864+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-09-28T22:24:00.883+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_MLcustomer_table> on 2023-09-27 00:00:00+00:00
[2023-09-28T22:24:00.890+0000] {standard_task_runner.py:55} INFO - Started process 73 to run task
[2023-09-28T22:24:00.894+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_tables', 'create_MLcustomer_table', 'scheduled__2023-09-27T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/process_data.py', '--cfg-path', '/tmp/tmp0n9jilvj']
[2023-09-28T22:24:00.895+0000] {standard_task_runner.py:83} INFO - Job 107: Subtask create_MLcustomer_table
[2023-09-28T22:24:00.972+0000] {task_command.py:376} INFO - Running <TaskInstance: create_tables.create_MLcustomer_table scheduled__2023-09-27T00:00:00+00:00 [running]> on host 20e0c20d2e1d
[2023-09-28T22:24:01.064+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_tables
AIRFLOW_CTX_TASK_ID=create_MLcustomer_table
AIRFLOW_CTX_EXECUTION_DATE=2023-09-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-27T00:00:00+00:00
[2023-09-28T22:24:01.079+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-09-28T22:24:01.085+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS machine_learning_customerchurn(
                state TEXT NULL,
                account_length INTEGER NULL,
                area_code INTEGER NULL,
                phone_number TEXT NULL,
                international_plan TEXT NULL,
                voice_mail_plan TEXT NULL,
                number_vmail_messages INTEGER NULL,
                total_day_minutes FLOAT NULL,
                total_day_calls INTEGER NULL,
                total_day_charge FLOAT NULL,
                total_eve_minutes FLOAT NULL,
                total_eve_calls INTEGER NULL,
                total_eve_charge FLOAT NULL,
                total_night_minutes FLOAT NULL,
                total_night_calls INTEGER NULL,
                total_night_charge FLOAT NULL,
                total_intl_minutes FLOAT NULL,
                total_intl_calls INTEGER NULL,
                total_intl_charge FLOAT NULL,
                customer_service_calls INTEGER NULL,
                churn BOOLEAN NULL
            );
        , parameters: None
[2023-09-28T22:24:01.087+0000] {postgres.py:96} INFO - NOTICE:  relation "machine_learning_customerchurn" already exists, skipping

[2023-09-28T22:24:01.098+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=create_tables, task_id=create_MLcustomer_table, execution_date=20230927T000000, start_date=20230928T222400, end_date=20230928T222401
[2023-09-28T22:24:01.147+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-09-28T22:24:01.170+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
